// 日本国憲法前文（ひらがな+記号のみ）
import { KanaString, JapaneseText } from './kanaUtils';

export type RubySegment = {
  text: JapaneseText;
  ruby: KanaString;
};

export type Sentence = {
  text: JapaneseText;
  kana: KanaString;
  segments: RubySegment[];
};

export const SENTENCES: Sentence[] = [
  {
    text: JapaneseText('われらは、全世界の国民が、ひとしく恐怖と欠乏から免かれ、平和のうちに生存する権利を有することを確認する。'),
    kana: KanaString('われらは、ぜんせかいのこくみんが、ひとしくきょうふとけつぼうからまぬかれ、へいわのうちにせいぞんするけんりをゆうすることをかくにんする。'),
    segments: [
      { text: JapaneseText('われらは、'), ruby: KanaString('われらは、') },
      { text: JapaneseText('全世界'), ruby: KanaString('ぜんせかい') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('国民'), ruby: KanaString('こくみん') },
      { text: JapaneseText('が、ひとしく'), ruby: KanaString('が、ひとしく') },
      { text: JapaneseText('恐怖'), ruby: KanaString('きょうふ') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('欠乏'), ruby: KanaString('けつぼう') },
      { text: JapaneseText('から'), ruby: KanaString('から') },
      { text: JapaneseText('免'), ruby: KanaString('まぬ') },
      { text: JapaneseText('かれ、'), ruby: KanaString('かれ、') },
      { text: JapaneseText('平和'), ruby: KanaString('へいわ') },
      { text: JapaneseText('のうちに'), ruby: KanaString('のうちに') },
      { text: JapaneseText('生存'), ruby: KanaString('せいぞん') },
      { text: JapaneseText('する'), ruby: KanaString('する') },
      { text: JapaneseText('権利'), ruby: KanaString('けんり') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('有'), ruby: KanaString('ゆう') },
      { text: JapaneseText('することを'), ruby: KanaString('することを') },
      { text: JapaneseText('確認'), ruby: KanaString('かくにん') },
      { text: JapaneseText('する。'), ruby: KanaString('する。') },
    ],
  },
  {
    text: JapaneseText('われらは、平和を維持し、専制と隷従、圧迫と偏狭を地上から永遠に除去しようと努めている国際社会において、名誉ある地位を占めたいと思う。'),
    kana: KanaString('われらは、へいわをいじし、せんせいとれいじゅう、あっぱくとへんきょうをちじょうからえいえんにじょきょしようとつとめているこくさいしゃかいにおいて、めいよあるちいをしめたいとおもう。'),
    segments: [
      { text: JapaneseText('われらは、'), ruby: KanaString('われらは、') },
      { text: JapaneseText('平和'), ruby: KanaString('へいわ') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('維持'), ruby: KanaString('いじ') },
      { text: JapaneseText('し、'), ruby: KanaString('し、') },
      { text: JapaneseText('専制'), ruby: KanaString('せんせい') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('隷従'), ruby: KanaString('れいじゅう') },
      { text: JapaneseText('、'), ruby: KanaString('、') },
      { text: JapaneseText('圧迫'), ruby: KanaString('あっぱく') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('偏狭'), ruby: KanaString('へんきょう') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('地上'), ruby: KanaString('ちじょう') },
      { text: JapaneseText('から'), ruby: KanaString('から') },
      { text: JapaneseText('永遠'), ruby: KanaString('えいえん') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('除去'), ruby: KanaString('じょきょ') },
      { text: JapaneseText('しようと'), ruby: KanaString('しようと') },
      { text: JapaneseText('努'), ruby: KanaString('つと') },
      { text: JapaneseText('めている'), ruby: KanaString('めている') },
      { text: JapaneseText('国際社会'), ruby: KanaString('こくさいしゃかい') },
      { text: JapaneseText('において、'), ruby: KanaString('において、') },
      { text: JapaneseText('名誉'), ruby: KanaString('めいよ') },
      { text: JapaneseText('ある'), ruby: KanaString('ある') },
      { text: JapaneseText('地位'), ruby: KanaString('ちい') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('占'), ruby: KanaString('し') },
      { text: JapaneseText('めたいと'), ruby: KanaString('めたいと') },
      { text: JapaneseText('思'), ruby: KanaString('おも') },
      { text: JapaneseText('う。'), ruby: KanaString('う。') },
    ],
  },
  {
    text: JapaneseText('われらは、いずれの国家も、自国のことのみに専念して他国を無視してはならないのであって、政治道徳の法則は、普遍的なものであり、この法則に従うことは、自国の主権を維持し、他国と対等関係に立とうとする各国の責務であると信ずる。'),
    kana: KanaString('われらは、いずれのこっかも、じこくのことのみにせんねんしてたこくをむししてはならないのであって、せいじどうとくのほうそくは、ふへんてきなものであり、このほうそくにしたがうことは、じこくのしゅけんをいじし、たこくとたいとうかんけいにたとうとするかっこくのせきむであるとしんずる。'),
    segments: [
      { text: JapaneseText('われらは、いずれの'), ruby: KanaString('われらは、いずれの') },
      { text: JapaneseText('国家'), ruby: KanaString('こっか') },
      { text: JapaneseText('も、'), ruby: KanaString('も、') },
      { text: JapaneseText('自国'), ruby: KanaString('じこく') },
      { text: JapaneseText('のことのみに'), ruby: KanaString('のことのみに') },
      { text: JapaneseText('専念'), ruby: KanaString('せんねん') },
      { text: JapaneseText('して'), ruby: KanaString('して') },
      { text: JapaneseText('他国'), ruby: KanaString('たこく') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('無視'), ruby: KanaString('むし') },
      { text: JapaneseText('してはならないのであって、'), ruby: KanaString('してはならないのであって、') },
      { text: JapaneseText('政治道徳'), ruby: KanaString('せいじどうとく') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('法則'), ruby: KanaString('ほうそく') },
      { text: JapaneseText('は、'), ruby: KanaString('は、') },
      { text: JapaneseText('普遍的'), ruby: KanaString('ふへんてき') },
      { text: JapaneseText('なものであり、この'), ruby: KanaString('なものであり、この') },
      { text: JapaneseText('法則'), ruby: KanaString('ほうそく') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('従'), ruby: KanaString('したが') },
      { text: JapaneseText('うことは、'), ruby: KanaString('うことは、') },
      { text: JapaneseText('自国'), ruby: KanaString('じこく') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('主権'), ruby: KanaString('しゅけん') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('維持'), ruby: KanaString('いじ') },
      { text: JapaneseText('し、'), ruby: KanaString('し、') },
      { text: JapaneseText('他国'), ruby: KanaString('たこく') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('対等関係'), ruby: KanaString('たいとうかんけい') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('立'), ruby: KanaString('た') },
      { text: JapaneseText('とうとする'), ruby: KanaString('とうとする') },
      { text: JapaneseText('各国'), ruby: KanaString('かっこく') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('責務'), ruby: KanaString('せきむ') },
      { text: JapaneseText('であると'), ruby: KanaString('であると') },
      { text: JapaneseText('信'), ruby: KanaString('しん') },
      { text: JapaneseText('ずる。'), ruby: KanaString('ずる。') },
    ],
  },
  {
    text: JapaneseText('日本国民は、恒久の平和を念願し、人間相互の関係を支配する崇高な理想を深く自覚するのであって、平和を愛する諸国民の公正と信義に信頼して、われらの安全と生存を保持しようと決意した。'),
    kana: KanaString('にほんこくみんは、こうきゅうのへいわをねんがんし、にんげんそうごのかんけいをしはいするすうこうなりそうをふかくじかくするのであって、へいわをあいするしょこくみんのこうせいとしんぎにしんらいして、われらのあんぜんとせいぞんをほじしようとけついした。'),
    segments: [
      { text: JapaneseText('日本国民'), ruby: KanaString('にほんこくみん') },
      { text: JapaneseText('は、'), ruby: KanaString('は、') },
      { text: JapaneseText('恒久'), ruby: KanaString('こうきゅう') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('平和'), ruby: KanaString('へいわ') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('念願'), ruby: KanaString('ねんがん') },
      { text: JapaneseText('し、'), ruby: KanaString('し、') },
      { text: JapaneseText('人間相互'), ruby: KanaString('にんげんそうご') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('関係'), ruby: KanaString('かんけい') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('支配'), ruby: KanaString('しはい') },
      { text: JapaneseText('する'), ruby: KanaString('する') },
      { text: JapaneseText('崇高'), ruby: KanaString('すうこう') },
      { text: JapaneseText('な'), ruby: KanaString('な') },
      { text: JapaneseText('理想'), ruby: KanaString('りそう') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('深'), ruby: KanaString('ふか') },
      { text: JapaneseText('く'), ruby: KanaString('く') },
      { text: JapaneseText('自覚'), ruby: KanaString('じかく') },
      { text: JapaneseText('するのであって、'), ruby: KanaString('するのであって、') },
      { text: JapaneseText('平和'), ruby: KanaString('へいわ') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('愛'), ruby: KanaString('あい') },
      { text: JapaneseText('する'), ruby: KanaString('する') },
      { text: JapaneseText('諸国民'), ruby: KanaString('しょこくみん') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('公正'), ruby: KanaString('こうせい') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('信義'), ruby: KanaString('しんぎ') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('信頼'), ruby: KanaString('しんらい') },
      { text: JapaneseText('して、われらの'), ruby: KanaString('して、われらの') },
      { text: JapaneseText('安全'), ruby: KanaString('あんぜん') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('生存'), ruby: KanaString('せいぞん') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('保持'), ruby: KanaString('ほじ') },
      { text: JapaneseText('しようと'), ruby: KanaString('しようと') },
      { text: JapaneseText('決意'), ruby: KanaString('けつい') },
      { text: JapaneseText('した。'), ruby: KanaString('した。') },
    ],
  },
  {
    text: JapaneseText('日本国民は、国家の名誉にかけ、全力をあげてこの崇高な理想と目的を達成することを誓う。'),
    kana: KanaString('にほんこくみんは、こっかのめいよにかけ、ぜんりょくをあげてこのすうこうなりそうともくてきをたっせいすることをちかう。'),
    segments: [
      { text: JapaneseText('日本国民'), ruby: KanaString('にほんこくみん') },
      { text: JapaneseText('は、'), ruby: KanaString('は、') },
      { text: JapaneseText('国家'), ruby: KanaString('こっか') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('名誉'), ruby: KanaString('めいよ') },
      { text: JapaneseText('にかけ、'), ruby: KanaString('にかけ、') },
      { text: JapaneseText('全力'), ruby: KanaString('ぜんりょく') },
      { text: JapaneseText('をあげてこの'), ruby: KanaString('をあげてこの') },
      { text: JapaneseText('崇高'), ruby: KanaString('すうこう') },
      { text: JapaneseText('な'), ruby: KanaString('な') },
      { text: JapaneseText('理想'), ruby: KanaString('りそう') },
      { text: JapaneseText('と'), ruby: KanaString('と') },
      { text: JapaneseText('目的'), ruby: KanaString('もくてき') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('達成'), ruby: KanaString('たっせい') },
      { text: JapaneseText('することを'), ruby: KanaString('することを') },
      { text: JapaneseText('誓'), ruby: KanaString('ちか') },
      { text: JapaneseText('う。'), ruby: KanaString('う。') },
    ],
  },
  {
    text: JapaneseText('そもそも国政は、国民の厳粛な信託によるものであって、その権威は国民に由来し、その権力は国民の代表者がこれを行使し、その福利は国民がこれを享受する。'),
    kana: KanaString('そもそもこくせいは、こくみんのげんしゅくなしんたくによるものであって、そのけんいはこくみんにゆらいし、そのけんりょくはこくみんのだいひょうしゃがこれをこうしし、そのふくりはこくみんがこれをきょうじゅする。'),
    segments: [
      { text: JapaneseText('そもそも'), ruby: KanaString('そもそも') },
      { text: JapaneseText('国政'), ruby: KanaString('こくせい') },
      { text: JapaneseText('は、'), ruby: KanaString('は、') },
      { text: JapaneseText('国民'), ruby: KanaString('こくみん') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('厳粛'), ruby: KanaString('げんしゅく') },
      { text: JapaneseText('な'), ruby: KanaString('な') },
      { text: JapaneseText('信託'), ruby: KanaString('しんたく') },
      { text: JapaneseText('によるものであって、その'), ruby: KanaString('によるものであって、その') },
      { text: JapaneseText('権威'), ruby: KanaString('けんい') },
      { text: JapaneseText('は'), ruby: KanaString('は') },
      { text: JapaneseText('国民'), ruby: KanaString('こくみん') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('由来'), ruby: KanaString('ゆらい') },
      { text: JapaneseText('し、その'), ruby: KanaString('し、その') },
      { text: JapaneseText('権力'), ruby: KanaString('けんりょく') },
      { text: JapaneseText('は'), ruby: KanaString('は') },
      { text: JapaneseText('国民'), ruby: KanaString('こくみん') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('代表者'), ruby: KanaString('だいひょうしゃ') },
      { text: JapaneseText('がこれを'), ruby: KanaString('がこれを') },
      { text: JapaneseText('行使'), ruby: KanaString('こうし') },
      { text: JapaneseText('し、その'), ruby: KanaString('し、その') },
      { text: JapaneseText('福利'), ruby: KanaString('ふくり') },
      { text: JapaneseText('は'), ruby: KanaString('は') },
      { text: JapaneseText('国民'), ruby: KanaString('こくみん') },
      { text: JapaneseText('がこれを'), ruby: KanaString('がこれを') },
      { text: JapaneseText('享受'), ruby: KanaString('きょうじゅ') },
      { text: JapaneseText('する。'), ruby: KanaString('する。') },
    ],
  },
  {
    text: JapaneseText('これは人類普遍の原理であり、この憲法は、かかる原理に基くものである。'),
    kana: KanaString('これはじんるいふへんのげんりであり、このけんぽうは、かかるげんりにもとづくものである。'),
    segments: [
      { text: JapaneseText('これは'), ruby: KanaString('これは') },
      { text: JapaneseText('人類'), ruby: KanaString('じんるい') },
      { text: JapaneseText('普遍'), ruby: KanaString('ふへん') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('原理'), ruby: KanaString('げんり') },
      { text: JapaneseText('であり、この'), ruby: KanaString('であり、この') },
      { text: JapaneseText('憲法'), ruby: KanaString('けんぽう') },
      { text: JapaneseText('は、かかる'), ruby: KanaString('は、かかる') },
      { text: JapaneseText('原理'), ruby: KanaString('げんり') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('基'), ruby: KanaString('もとづ') },
      { text: JapaneseText('くものである。'), ruby: KanaString('くものである。') },
    ],
  },
  {
    text: JapaneseText('われらは、これに反する一切の憲法、法令及び詔勅を排除する。'),
    kana: KanaString('われらは、これにはんするいっさいのけんぽう、ほうれいおよびしょうちょくをはいじょする。'),
    segments: [
      { text: JapaneseText('われらは、これに'), ruby: KanaString('われらは、これに') },
      { text: JapaneseText('反'), ruby: KanaString('はん') },
      { text: JapaneseText('する'), ruby: KanaString('する') },
      { text: JapaneseText('一切'), ruby: KanaString('いっさい') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('憲法'), ruby: KanaString('けんぽう') },
      { text: JapaneseText('、'), ruby: KanaString('、') },
      { text: JapaneseText('法令'), ruby: KanaString('ほうれい') },
      { text: JapaneseText('及'), ruby: KanaString('およ') },
      { text: JapaneseText('び'), ruby: KanaString('び') },
      { text: JapaneseText('詔勅'), ruby: KanaString('しょうちょく') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('排除'), ruby: KanaString('はいじょ') },
      { text: JapaneseText('する。'), ruby: KanaString('する。') },
    ],
  },
  {
    text: JapaneseText('日本国民は、正当に選挙された国会における代表者を通じて行動し、われらとわれらの子孫のために、諸国民との協和による成果と、わが国全土にわたって自由のもたらす恵沢を確保し、政府の行為によって再び戦争の惨禍が起ることのないようにすることを決意し、ここに主権が国民に存することを宣言し、この憲法を確定する。'),
    kana: KanaString('にほんこくみんは、せいとうにせんきょされたこっかいにおけるだいひょうしゃをつうじてこうどうし、われらとわれらのしそんのために、しょこくみんとのきょうわによるせいかと、わがくにぜんどにわたってじゆうのもたらすけいたくをかくほし、せいふのこういによってふたたびせんそうのさんかがおこることのないようにすることをけついし、ここにしゅけんがこくみんにそんすることをせんげんし、このけんぽうをかくていする。'),
    segments: [
      { text: JapaneseText('日本国民'), ruby: KanaString('にほんこくみん') },
      { text: JapaneseText('は、'), ruby: KanaString('は、') },
      { text: JapaneseText('正当'), ruby: KanaString('せいとう') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('選挙'), ruby: KanaString('せんきょ') },
      { text: JapaneseText('された'), ruby: KanaString('された') },
      { text: JapaneseText('国会'), ruby: KanaString('こっかい') },
      { text: JapaneseText('における'), ruby: KanaString('における') },
      { text: JapaneseText('代表者'), ruby: KanaString('だいひょうしゃ') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('通'), ruby: KanaString('つう') },
      { text: JapaneseText('じて'), ruby: KanaString('じて') },
      { text: JapaneseText('行動'), ruby: KanaString('こうどう') },
      { text: JapaneseText('し、われらとわれらの'), ruby: KanaString('し、われらとわれらの') },
      { text: JapaneseText('子孫'), ruby: KanaString('しそん') },
      { text: JapaneseText('のために、'), ruby: KanaString('のために、') },
      { text: JapaneseText('諸国民'), ruby: KanaString('しょこくみん') },
      { text: JapaneseText('との'), ruby: KanaString('との') },
      { text: JapaneseText('協和'), ruby: KanaString('きょうわ') },
      { text: JapaneseText('による'), ruby: KanaString('による') },
      { text: JapaneseText('成果'), ruby: KanaString('せいか') },
      { text: JapaneseText('と、わが'), ruby: KanaString('と、わが') },
      { text: JapaneseText('国'), ruby: KanaString('くに') },
      { text: JapaneseText('全土'), ruby: KanaString('ぜんど') },
      { text: JapaneseText('にわたって'), ruby: KanaString('にわたって') },
      { text: JapaneseText('自由'), ruby: KanaString('じゆう') },
      { text: JapaneseText('のもたらす'), ruby: KanaString('のもたらす') },
      { text: JapaneseText('恵沢'), ruby: KanaString('けいたく') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('確保'), ruby: KanaString('かくほ') },
      { text: JapaneseText('し、'), ruby: KanaString('し、') },
      { text: JapaneseText('政府'), ruby: KanaString('せいふ') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('行為'), ruby: KanaString('こうい') },
      { text: JapaneseText('によって'), ruby: KanaString('によって') },
      { text: JapaneseText('再'), ruby: KanaString('ふたた') },
      { text: JapaneseText('び'), ruby: KanaString('び') },
      { text: JapaneseText('戦争'), ruby: KanaString('せんそう') },
      { text: JapaneseText('の'), ruby: KanaString('の') },
      { text: JapaneseText('惨禍'), ruby: KanaString('さんか') },
      { text: JapaneseText('が'), ruby: KanaString('が') },
      { text: JapaneseText('起'), ruby: KanaString('おこ') },
      { text: JapaneseText('ることのないようにすることを'), ruby: KanaString('ることのないようにすることを') },
      { text: JapaneseText('決意'), ruby: KanaString('けつい') },
      { text: JapaneseText('し、ここに'), ruby: KanaString('し、ここに') },
      { text: JapaneseText('主権'), ruby: KanaString('しゅけん') },
      { text: JapaneseText('が'), ruby: KanaString('が') },
      { text: JapaneseText('国民'), ruby: KanaString('こくみん') },
      { text: JapaneseText('に'), ruby: KanaString('に') },
      { text: JapaneseText('存'), ruby: KanaString('そん') },
      { text: JapaneseText('することを'), ruby: KanaString('することを') },
      { text: JapaneseText('宣言'), ruby: KanaString('せんげん') },
      { text: JapaneseText('し、この'), ruby: KanaString('し、この') },
      { text: JapaneseText('憲法'), ruby: KanaString('けんぽう') },
      { text: JapaneseText('を'), ruby: KanaString('を') },
      { text: JapaneseText('確定'), ruby: KanaString('かくてい') },
      { text: JapaneseText('する。'), ruby: KanaString('する。') },
    ],
  },
];

export const ALL_SENTENCE: Sentence = {
  text: JapaneseText(SENTENCES.map(s => s.text).join('')),
  kana: KanaString(SENTENCES.map(s => s.kana).join('')),
  segments: SENTENCES.flatMap(s => s.segments),
};

// 各段落の先頭セグメントインデックス（段落境界）
export const PARAGRAPH_SEGMENT_OFFSETS: number[] = (() => {
  const offsets: number[] = [];
  let acc = 0;
  for (const s of SENTENCES) {
    offsets.push(acc);
    acc += s.segments.length;
  }
  return offsets;
})();
